IndependentProj/Controllers/EmployeeController.cs
using IndependentProj.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace IndependentProj.Controllers
{
    public class EmployeeController : Controller
    {
        private IEmployeeRepository _repository;
        public EmployeeController(IEmployeeRepository repository)
        {
            _repository = repository;

        }
        public ViewResult Index() => View(_repository.Employees);//.Include(e => e.EmployeeProject).ThenInclude(e => e.Project)
        public ViewResult AddEmployee() 
        {
            ViewBag.AllProjects = _repository.AllProjects;
            ViewBag.NoHeadOfProject = _repository.AllProjects.Where(p => p.EmployeeProject.All(p => p.Employee.HeadOfProjectID != p.ProjectID)); // ???
            return View(new Employee());
        }

        [HttpPost]
        public IActionResult AddEmployee(Employee employee)
        {
            if (ModelState.IsValid)
            {
                _repository.Add(employee);
                return RedirectToAction("Index");
            }
            else
            {
                return View(employee);
            }

        }
        [HttpGet]
        public ViewResult EditEmployee(int employeeId)
        {
            ViewBag.AllProjects = _repository.AllProjects;
            ViewBag.NoHeadOfProject = _repository.AllProjects.Where(p => p.EmployeeProject.All(p => p.Employee.HeadOfProjectID != p.ProjectID));
            return View(_repository.Employees.FirstOrDefault(e => e.EmployeeID == employeeId));
        }
        [HttpPost]
        public IActionResult EditEmployee(Employee employee)
        {
            if (ModelState.IsValid)
            {
                _repository.Edit(employee);
                return RedirectToAction("Index");
            }
            else
            {
                return View(employee);
            }
        }
        [HttpPost]
        public RedirectToActionResult DeleteEmployee(int employeeId)
        {
            _repository.Delete(employeeId);
            return RedirectToAction("Index");
        }
    }
}

IndependentProj/Controllers/ProjectController.cs
using IndependentProj.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace IndependentProj.Controllers
{
    public class ProjectController : Controller
    {
        private IProjectRepository _repository;
        private List<EmployeeProject> _employeeProjects;
        public ProjectController(IProjectRepository repository)
        {
            _repository = repository;
        }

        public ViewResult Index() => View(_repository.Projects);//.Include(p => p.EmployeeProject).ThenInclude(p => p.Employee)

        public ViewResult AddProject()
        {
            ViewBag.AllEmployees = _repository.AllEmployees;
            ViewBag.NoHeadOfProject = _repository.AllEmployees.Where(e => e.EmployeeProject.All(e => e.Project.HeadOfProjectID != e.EmployeeID));
            return View(new Project());
        }

            [HttpPost]
        public IActionResult AddProject(Project project)
        {
            if (ModelState.IsValid)
            {

                _repository.Add(project);
                return RedirectToAction("Index");
            }
            else
            {
                return View(project);
            }
            
        }
        [HttpGet]
        public ViewResult EditProject(int projectId)
        {
            ViewBag.AllEmployees = _repository.AllEmployees;
            ViewBag.NoHeadOfProject = _repository.AllEmployees.Where(e => e.EmployeeProject.All(e => e.Project.HeadOfProjectID != e.EmployeeID));
            return View( _repository.Projects.FirstOrDefault(p => p.ProjectID == projectId));
        }
        [HttpPost]
        public IActionResult EditProject(Project project)
        {

            if (ModelState.IsValid)
            {
                _repository.Edit(project);
                return RedirectToAction("Index");
            }
            else
            {
                return View(project);
            }

        }
        [HttpPost]
        public RedirectToActionResult DeleteProject(int projectId)
        {
            _repository.Delete(projectId);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ViewResult OrderByPriority(Priority priority)
        {
            if(priority != _repository.Projects.Min(p => p.Priority)) return View("Index", _repository.Projects.OrderBy(p => p.Priority));
            else return View("Index", _repository.Projects.OrderByDescending(p => p.Priority));
        }
        [HttpGet]
        public ViewResult OrderByStartDate(DateTime date)
        {
            if (date != _repository.Projects.Min(p => p.StartDate)) return View("Index", _repository.Projects.OrderBy(p => p.StartDate));
            else return View("Index", _repository.Projects.OrderByDescending(p => p.StartDate));
        }
        [HttpGet]
        public ViewResult FilterDate(DateTime startDate_1, DateTime startDate_2)
        {
            var re = startDate_1;
            var res = startDate_2;

            return View("Index");
        }
    }

}

IndependentProj/Views/Shared/_AddLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/bootstrap.css" />
    <style>
        .input-validation-error { border-color:red; background-color: #fee;}
    </style>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="https://rawgit.com/RobinHerbots/Inputmask/5.x/dist/jquery.inputmask.js"></script>
    <script>
        $(document).ready(function() {
            $("#phone").inputmask('999 999-99-99');
        });
    </script>
</head>
<body class="m-1 p-1">
    <div class="navbar navbar-inverse navbark-dark bg-dark">
        <h3 class="text-white">@ViewBag.Title</h3>
    </div>
    @*TODO: Done with this*@
    @if (TempData["message"] != null)
    {
        <div class="alert alert-success mt-1">@TempData["message"]</div>
    }
    @RenderBody()
</body>
</html>

IndependentProj/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/bootstrap.min.css" />
     <link rel="stylesheet" asp-href-include="/lib/font-awesome/css/*.css"/>
</head>
<body class="m-1 p-1">
    <div class="navbar navbar-inverse navbar-dark bg-dark" role="navigation">
        <div class="container-fluid">
            <a class="navbar-brand">Project Archive</a>
            <p class="text-white">@ViewBag.Title</p>
            <div class="d-flex text-center">
                <a class="btn btn-secondary btn-sm navbar-btn" asp-controller="Project" asp-action="Index">Project List</a>
                <a class="btn btn-secondary btn-sm navbar-btn" asp-controller="Employee" asp-action="Index">Employee List</a>
            </div>
        </div>
    </div>
    <div>
        @RenderBody()
    </div>
</body>
</html>